num1= int(input("Enter first number: "))
num2= int(input("Enter second number: "))
sum=int(num1)+int(num2)
difference=int(num1)-int(num2)  
product=int(num1)*int(num2)
quotient=float(num1)/float(num2)
print("Addition: ", sum)
print("Subtraction: ", difference)
print("Multiplication: ", product)
print("Division: ", quotient)
